services:
  db:
    image: postgres:15-alpine
    container_name: sarisync_db
    restart: always

    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: sarisync_main

    ports:
      - "5432:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: